# Generated by Django 4.1.3 on 2022-12-20 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_limit', models.FloatField()),
                ('current_balance', models.FloatField()),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_type.accounttype')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
