# Generated by Django 4.1.3 on 2022-12-20 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_number',
             field=models.CharField(max_length=15),
        ),
    ]
