# Generated by Django 4.1.3 on 2022-12-20 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('customer', '0002_customer_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_amount', models.FloatField()),
                ('date_of_joining', models.DateField()),
                ('work_status', models.CharField(max_length=25)),
                ('designation', models.CharField(max_length=25)),
                ('official_email', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=25)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
