# Generated by Django 4.1.3 on 2022-12-21 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_customer_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('number', models.CharField(max_length=15)),
                ('expiry_date', models.DateField()),
                ('cvv_code', models.IntegerField(max_length=3)),
                ('status', models.CharField(max_length=10)),
                ('is_deleted', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'card',
            },
        ),
    ]
