# Generated by Django 4.1.4 on 2022-12-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='road',
        ),
        migrations.RemoveField(
            model_name='address',
            name='taluka',
        ),
    ]
