# Generated by Django 4.1.3 on 2022-12-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('loan_intrest_rate', models.FloatField()),
                ('saving_intrest_rate', models.FloatField()),
            ],
            options={
                'db_table': 'account_type',
            },
        ),
    ]
