# Generated by Django 4.1.4 on 2022-12-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('user_id', models.FloatField()),
                ('department_id', models.FloatField()),
                ('designation', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'manager',
            },
        ),
    ]
